// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHMxlRrigIXcfS1EQE0O-w0AXqVDDMeYM',
    appId: '1:127730135512:web:50258ef7d039d38b2182ad',
    messagingSenderId: '127730135512',
    projectId: 'binm8-56751',
    authDomain: 'binm8-56751.firebaseapp.com',
    storageBucket: 'binm8-56751.firebasestorage.app',
    measurementId: 'G-7JZVKQ2ZW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaA_4Oytilc2wOZYfgeb_KrNALZExfYv0',
    appId: '1:127730135512:android:e4905fec969a400d2182ad',
    messagingSenderId: '127730135512',
    projectId: 'binm8-56751',
    storageBucket: 'binm8-56751.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSj1SUi8Gd6OeG344ZDF4vbM59Dz1OD9k',
    appId: '1:127730135512:ios:37c478c0ca8d8a3a2182ad',
    messagingSenderId: '127730135512',
    projectId: 'binm8-56751',
    storageBucket: 'binm8-56751.firebasestorage.app',
    iosBundleId: 'com.bin.app.binApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSj1SUi8Gd6OeG344ZDF4vbM59Dz1OD9k',
    appId: '1:127730135512:ios:37c478c0ca8d8a3a2182ad',
    messagingSenderId: '127730135512',
    projectId: 'binm8-56751',
    storageBucket: 'binm8-56751.firebasestorage.app',
    iosBundleId: 'com.bin.app.binApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHMxlRrigIXcfS1EQE0O-w0AXqVDDMeYM',
    appId: '1:127730135512:web:2480a94406ecfe0f2182ad',
    messagingSenderId: '127730135512',
    projectId: 'binm8-56751',
    authDomain: 'binm8-56751.firebaseapp.com',
    storageBucket: 'binm8-56751.firebasestorage.app',
    measurementId: 'G-WYPCX5P865',
  );

}